name: example
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  core:
    path: packages/core
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.4
  go_router: ^14.8.1
  intl: ^0.19.0
  logger: ^2.5.0
  provider: ^6.1.4

dev_dependencies:
  bloc_test: ^9.1.7
  change_app_package_name: ^1.5.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1
  melos: ^6.3.2
  mocktail: ^1.0.4
  rename_app: ^1.6.2
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
