name: lune
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7
  flutter_native_splash: ^2.4.4
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  hive: ^2.2.3
  http_client:
    path: packages/http_client
  image_picker: ^1.1.2
  intl: ^0.19.0
  logger: ^2.5.0
  material_color_utilities: ^0.11.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  provider: ^6.1.4
  reactive_forms: ^18.0.0
  smooth_page_indicator: ^1.2.1
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.15
  change_app_package_name: ^1.5.0
  flutter_gen_runner: ^5.10.0
  flutter_test:
    sdk: flutter
  icons_launcher: ^3.0.1
  melos: ^6.3.2
  mocktail: ^1.0.4
  rename_app: ^1.6.2
  very_good_analysis: ^6.0.0

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: false

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/files/
    - assets/dark/icons/
    - assets/dark/images/
    - assets/light/icons/
    - assets/light/images/