name: core
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.17
  go_router: ^14.8.1
  google_fonts: ^6.2.1
  material_color_utilities: ^0.11.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0

flutter:
  assets:
    - assets/dark/icons/
    - assets/dark/images/
    - assets/light/icons/
    - assets/light/images/